### ISSUE TITLE
Testing library with separated angular cli project using npm link

### ISSUE THREAD

**Issue by rvalenciano** [yp2/ngx-cron-jobs#13]
Hi @yp2 ,

I've been trying to link this library to a separated angular cli project. I know that to develop we could use the embedded project in the library, but to avoid potential issues I would also like to develop it in a traditional way.

So I created [this project:](https://github.com/rvalenciano/test-ngx-cron-jobs)

which works perfectly with production distribution (adding npm install --save ngx-cron-jobs)

However, doing inside this project:

```shell
npm uninstall ngx-cron-jobs
```

and then in other tab, I go to the library and do:

```shell
npm run build:lib
cd dist
npm link
```
and then in the other console tab inside the test project

```shell
npm link ngx-cron-jobs
```

it compiles correctly, however when using it:

<img width="1420" alt="screen shot 2017-12-06 at 2 16 38 pm" src="https://user-images.githubusercontent.com/5366444/33683579-f7962df4-da90-11e7-81a4-1feaa170bc9f.png">

They talk about something related [here](https://github.com/angular/angular-cli/issues/8677): however none of the suggestions worked.

Any idea of what I'm doing wrong?

**Comment by yp2** [comment]
Why you are using npm link? Maybe you should install this package from github repo 
```
npm install rvalenciano/ngx-cron-jobs
```
or
```
npm install yp2/ngx-cron-jobs
```
When you uninstall it from your project webpack doesn't bundle it.
