### ISSUE TITLE
Transfer original repo?

### ISSUE THREAD

**Issue by rvalenciano** [yp2/ngx-cron-jobs#19]
Hey @yp2 , I was thinking about transfering the original repo to you so you don't have to keep working in the fork. What do you think? The original repo in github should be from where the npm/yarn package is pushed.

Best

**Comment by yp2** [comment]
Hi, why not. This is a good idea.

**Comment by rvalenciano** [comment]
I tried but I cannot because there is a fork with the same name of the repo. We can:

1. I rename the original repo then transfer.
2. You merge latest changes of the fork, then you delete the fork and I transfer the repo.

Which way do you prefer?

**Comment by yp2** [comment]
Hi, please rename orginal repo.

**Comment by yp2** [comment]
@rvalenciano what about this issue

**Comment by rvalenciano** [comment]
This is weird. I still cannot transfer the repo. I renamed the original repo as you can see in the URL:

https://github.com/rvalenciano/ngx-cron-jobs-orig

When I try to transfer:

<img width="797" alt="screen shot 2018-06-24 at 12 03 45 pm" src="https://user-images.githubusercontent.com/5366444/41822025-ae9bd51e-77a6-11e8-824a-37e2ff6d9adb.png">

**Comment by yp2** [comment]
May be delete this repo or [this](https://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository)

**Comment by yp2** [comment]
Hi,
I will delete this repo and create new one.
