### ISSUE TITLE
Cannot redeclare block-scoped variable 'ngDevMode'.

### ISSUE THREAD

**Issue by maxkorz** [yp2/ngx-cron-jobs#21]
Hello. I'm getting this error with Angular 6.x:
```
ERROR in Error during template compile of 'Ng2DropdownMenu'
  Function calls are not supported in decorators but 'trigger' was called.
node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/ngx-cron-jobs/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
```

According to this discussion https://github.com/angular/angular/issues/21670#issuecomment-359752703 the library should not have a direct dependency on `@angular/core`. But I'm not sure that this is the cause of the problem. Could you please investigate?

**Comment by maarten-vandevelde** [comment]
I have the same problem and it is indeed the angualr version. Because this module dependes on Angualr 5.x, Angular 5 gets compiled into the application alongside Angular 6. Updating the dependencies to be peer dependencies  to Angualr 6.x should fix this problem.

` "peerDependencies": {
    "@angular/common": "6.x",
    "@angular/core": "6.x",
    "@angular/forms": "6.x",
    "@angular/platform-browser": "6.x",
    "rxjs": "6.x"
  },`

**Comment by yp2** [comment]
Fixed - peer dependencies with angular version 5.
