### ISSUE TITLE
Support RxJS v6 and Angular 6

### ISSUE THREAD

**Issue by maxkorz** [yp2/ngx-cron-jobs#23]
I'm getting error
`node_modules/ngx-cron-jobs/src/app/lib/cron-jobs/cron-jobs.component.d.ts(5,10): error TS2305: Module '"node_modules/rxjs/Observable"' has no exported member 'Observable'.
`

Angular 6 depends on RxJS v6. Please update the plugin.

**Comment by rvalenciano** [comment]
Hi, I can work on this.

Best

**Comment by yp2** [comment]
Yes. If you have a time. We will end up with two  version of packege. One with support for rxjs 6 and another one with support for rxjs 5.x

**Comment by maxkorz** [comment]
@yp2 I think you can bump the major version and drop support for rjx 5.x. All most-used plugins don't support Angular 5 and rxjs 5 anymore (such as ng-bootstrap, primeng, Angular2-Toaster, and other)

**Comment by yp2** [comment]
Maybe when ngrx/entity will support rxjs 6. I use cron jobs in project along with ngrx/platform. So I'm not plan to support rxjs 6 and drop support for rxjs 5

**Comment by maxkorz** [comment]
@yp2 https://github.com/ngrx/platform/blob/master/CHANGELOG.md it does support Angular 6 and RxJS 6 since 6.0.0-beta.0 (2018-03-31), and stable 6.0.0 version was released 28 days ago.

**Comment by yp2** [comment]
Thanks for info. Recently I faild with update to Angular 6 error with ngrx/entity and its dependency. I have to check this update process again. After this I will have to take care with this update to rxjs 6 version.

BTW. This is an open source plugin.

**Comment by rvalenciano** [comment]
@maxkorz @yp2 PR opened.

https://github.com/yp2/ngx-cron-jobs/pull/25

**Comment by yp2** [comment]
@rvalenciano your PR is in review.

**Comment by yp2** [comment]
New package is available on npm - 6.4.9 should support Angular 6. Go ahead and test it in projects. 

@rvalenciano I will leave branch angular_6 main branch for development with Angular 6 and branch angular_5 as main branch for development for Angular 5. This branches should be source branches for new features.

**Comment by rvalenciano** [comment]
BTW great post of working with angular 6 and 5 versions.

https://blog.angularindepth.com/angular-5-or-angular-6-yes-please-d71b08b5e59b
