### ISSUE TITLE
How can i change styles and text?

### ISSUE THREAD

**Issue by nachocoig** [yp2/ngx-cron-jobs#24]
Basically, i need to customize texts, styles from your component.

My language is Spanish, and i need put all words in Spanish. 

I dont know how can i do it.

Can u help me?

PD: sorry for my english

**Comment by rvalenciano** [comment]
Hi @nachocoig we would have to add https://github.com/ngx-translate/core to this package.

Maybe you want to add a PR with this work done? Currently I've limited time to work on this.

**Comment by yp2** [comment]
@nachocoig like @rvalenciano wrote please provide us PR with translation support.
@nachocoig styles: I update Readme of project. You can use bootstrap layout or original one wrote by @rvalenciano. To change style you can use ::ng-deep selector more [here](https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep)
