### ISSUE TITLE
Angular 4 issue

### ISSUE THREAD

**Issue by winglo** [yp2/ngx-cron-jobs#26]
It looks like that the latest version doesn't support Angular 4. Do you know which version of ngx-cron-jobs i should use?

Thanks

**Comment by yp2** [comment]
Hi,
version 6.4.9 has support of Angular 6. If you want to use it with Angular below version 6 you should use version 0.4.9

**Comment by winglo** [comment]
Thanks. I just tried 0.4.9 and it has a warning of requiring angular 5.

**Comment by yp2** [comment]
It's a warning not an error. I should work.

**Comment by winglo** [comment]
Great! It works.thx
