### ISSUE TITLE
Angular 13 support

### ISSUE THREAD

**Issue by AndreyChayko** [yp2/ngx-cron-jobs#49]
Hey guys
How about upgrading up to 13?

**Comment by madsthom** [comment]
Let's do this. @AndreyChayko should I go for Angular 14 now that this is out?

**Comment by AndreyChayko** [comment]
@madsthom definitely dude, massive thank you 😊

**Comment by madsthom** [comment]
@AndreyChayko It should now be upgraded! You can get the lastest by running:
`npm install ngx-cron-jobs@latest` or `yarn add ngx-cron-jobs@lastest`
