### ISSUE TITLE
UI support for "every nth" interval

### ISSUE THREAD

**Issue by lovelldies** [yp2/ngx-cron-jobs#54]
It would be nice if the form supported options like `*/5 * * * *` ([every 5th minute](https://crontab.guru/#*/5_*_*_*_*)).

**Comment by madsthom** [comment]
I will try and work on this. But if you want a go at it yourself, go ahead and submit a PR!

**Comment by AhsanAyaz** [comment]
@madsthom if I'm correct, this means providing the following:
- Every nth minute
- Every nth hours at X minutes past
- Every nth day at X hours and Y minutes. And so on.
Is that accurate? Because that means an entire feature rather than minor enhancement.
I'm happy to introduce a PR for just every nth minute!

**Comment by lovelldies** [comment]
> I'm happy to introduce a PR for just every nth minute!

This would be sufficient, at least for my use case.

**Comment by madsthom** [comment]
@AhsanAyaz you can go ahead with this. 👍🏼 I am currently investigating a problem with the angular 14 upgrade.

**Comment by AhsanAyaz** [comment]
@madsthom , already submitted a PR for this 🙂 
#62

**Comment by madsthom** [comment]
Sorry, I totally missed that. 😁 - I will review tonight. 👍🏼

**Comment by lovelldies** [comment]
@AhsanAyaz / @madsthom thanks for looking into this!

**Comment by madsthom** [comment]
@lovelldies: Please open this again if it does not work as intended.

**Comment by lovelldies** [comment]
Apologies for the late response. I was on vacation.

Also thanks for working on this. I noticed some unexpected behavior.

Selecting **Minute** and **5th** generates an extra **?** at the end. If I'm not mistaken, that seems to be an invalid cron format.

![image](https://user-images.githubusercontent.com/7194108/201304598-78e49854-0ca8-4ad2-8b83-0dbfbdf17d07.png)

Also if I paste */5 * * * * into the textbox, it does not reflect in the selection form.

![image](https://user-images.githubusercontent.com/7194108/201305380-cc0a2b0a-74ee-46c0-a172-c4ced3128c99.png)

I shall re-open the request after I've heard your comments.
