### ISSUE TITLE
Not working for Angular 14

### ISSUE THREAD

**Issue by AndreyChayko** [yp2/ngx-cron-jobs#61]
@madsthom hi

It seems the new version is not exported correctly

I'm getting 

```error TS2307: Cannot find module 'ngx-cron-jobs' or its corresponding type declarations.```
```14 import { CronJobsModule } from 'ngx-cron-jobs';```

when trying to compile

**Comment by madsthom** [comment]
Hi - thank you for writing back. I will look into this ASAP. Its the first time I build it to npm registry, maybe something went wrong. The demo page uses the newest version and works fine. 

Maybe Angular 14 requires a different way of exporting the module. I will get back to you @AndreyChayko !😎

**Comment by AndreyChayko** [comment]
@madsthom just wondering if you was able to find anything about this? :)
I'm just doing a migration for our app and everything is done except this one, massive thank you for the help in advance dude!

**Comment by AndreyChayko** [comment]
@madsthom 

https://www.youtube.com/clip/Ugkx4UdnbV4rxN9NYNiun9xuG_1HDD_2kIwW

**Comment by madsthom** [comment]
@AndreyChayko have not had time yet to figure out the fix. To busy the ordinary day job. The demo page uses it and works. Feel free to try and fix it if you have time.

**Comment by madsthom** [comment]
I've looked at it now. But can't figure out why the CronJobModule is not exported... Maybe something new for angular 14 i've missed?

**Comment by AndreyChayko** [comment]
@madsthom I don't know either, will try to figure out as well

**Comment by AndreyChayko** [comment]
@madsthom 
I found the problem
It seems you've published the package in not some correct way
so here is what  is expected to have inside node_modules folder
![image](https://user-images.githubusercontent.com/13365024/195690930-4fc4905d-9349-430f-a0a6-66faec8acb1d.png)

and this is what we have actually now:
![image](https://user-images.githubusercontent.com/13365024/195690973-afa41972-8c43-49cd-a29a-1cbddcf5c1eb.png)


It is very weird but build:lib task fails to run so I decided to make a drafted PR with some cleaning stuff
feel free to change whatever you want there

Please take a look #64

**Comment by madsthom** [comment]
You are insane dude. Thank you so much for looking into this. Let me take a look at the pr and make another build to npm registry if everything works as expected! 🎉

**Comment by madsthom** [comment]
@AndreyChayko: Can you test with the latest version 14.2.6? - I created a new angular app with `ng new` and imported and used the package and it works (the things that i tested). And again thank you for your contribution.

**Comment by AndreyChayko** [comment]
@madsthom it works as expected now, checked the cases in our app everything works fine, thank you!
