### ISSUE TITLE
UI support for "every nth" minute

### ISSUE THREAD

**Issue by AhsanAyaz** [yp2/ngx-cron-jobs#62]
This is inspired from #54. But that is a HUGE effort to do as it requires possible implementation of all existing options (hours, minutes, days, weeks). Also, with a lot more complex situations.
But every nth minute is probably a good start in the direction suggested in #54 .
So it would be nice to implement it alongside the "Minute" selection. It can be every minute. Or every 5th minute etc.

**Comment by lovelldies** [comment]
Thanks for looking into this @AhsanAyaz !
