### ISSUE TITLE
Angular 15  + RxJS ^7.4.x Support

### ISSUE THREAD

**Issue by chrisweight** [yp2/ngx-cron-jobs#71]
I'm using RxJS 7.8.0 and this throws a peer-dependency error when installing, can we please have an updated release to work against Ng-15 + latest RxJS?

**Comment by madsthom** [comment]
@chrisweight Latest release removes peerDeps and upgrades to ng 15. Does this fix your issue?

**Comment by chrisweight** [comment]
> @chrisweight Latest release removes peerDeps and upgrades to ng 15. Does this fix your issue?

Not sure! I'll try and look at this when I get back to the project that was consuming this dependency, cheers for getting to it though!
